HOST = "irc.chat.twitch.tv"
PORT = 80
WHISPERHOST = "199.9.253.119"
WHISPERPORT = 443
PASS = "oauth:xDDDDDDDDDDD"
IDENT = "nuulsbot"
CHANNEL = input("channel: ")
ADMINS = ["nuuls", "nickfoon"]
BANPHRASES = [".", "superlongmessage", "longmessage"]