HOST = "irc.chat.twitch.tv"
PORT = 80
GROUPHOST = "199.9.253.119"
GROUPPORT = 443
PASS = "oauth:ayylmao"
IDENT = "nuulsbot"
CHANNEL = ["nuuls", "nymn_hs", "gempir", "pajlada"]
ADMIN = "nuuls"
BANPHRASES = "."
